apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: easy-kanban-nfs
  nfs:
    server: 10.99.114.55
    path: "/exports/registry"
  mountOptions:
    - vers=3
    - nolock
    - hard
    - intr

