apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-pvc
  namespace: easy-kanban
spec:
  containers:
  - name: test
    image: ubuntu:22.04
    command: ["sleep", "3600"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /mnt/nfs
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: easy-kanban-shared-pvc


